#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/phil/.Xmodmap"
pkill -f testwallpaper
pkill -f sleep

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.
#~/.config/openbox/mem.sh | lemonbar -f "Roboto Medium:size=12" &
fbpanel -p abc &
~/.fluxbox/testwallpaper &
#xcompmgr &

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/phil/.fluxbox/log"
