#!/usr/bin/env bash

#pgrep -x sxhkd > /dev/null || 

sxhkd -c /home/phil/.config/bspwm/sxhkdrc &

#killall testwallpaper
#killall lxpolkit
#killall xcompmgr

~/.config/bspwm/testwallpaper &

setxkbmap gb &
lxpolkit &
xcompmgr -c &

#$HOME/.config/polybar/launch.sh
######PATH not set yet############
~/.local/bin/succade &

bspc monitor -d I II III IV V

bspc config border_width         4
bspc config window_gap          8

bspc config focused_border_color "#FF0000"
bspc config top_padding 25
bspc config focus_follows_pointer true
#####bspc config initial_polarity second_child
#####bspc config automatic_scheme longest_side

##bspc config automatic_scheme spiral
##bspc config automatic_scheme longest_side
##bspc config initial_polarity second_child

#bspc config history_aware_focus	false
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config center_pseudo_tiled true
 
# Automatic Splitting Settings
bspc config automatic_scheme	spiral
bspc config initial_polarity	first_child





bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
#bspc rule -a firefox desktop=^2
#bspc rule -a Geany desktop=^3
bspc rule -a Xfce4-terminal state=floating
