#!/usr/bin/env bash

pkill -f testwallpaper
pkill -f sleep

export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"


#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down


#boot compton or picom if it exists
xcompmgr &
sxhkd -c /home/phil/.config/leftwm/themes/current/sxhkdrc &
/home/phil/.config/leftwm/themes/current/testwallpaper &


#set the theme.toml config
echo "LoadTheme $SCRIPTPATH/theme.toml" > $XDG_RUNTIME_DIR/leftwm/commands.pipe


#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale $SCRIPTPATH/background.jpg
fi

index=0
leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' | while read size
do 
   leftwm-state -w $index -t $SCRIPTPATH/template.liquid | xmobar -p "$size" $SCRIPTPATH/xmobar-config.hs &
   let index=index+1
done
/home/phil/.config/leftwm/themes/current/cursor.sh &


#pkill -f xmobar
#/home/phil/.config/leftwm/themes/mypolybar/launch.sh
