#!/usr/bin/env bash

#curl wttr.in/Caerphilly?format="%l+%C+%f" > /home/phil/.config/polybar/scripts/weatherinfo

echo $(curl wttr.in/Caerphilly?format="%l+%C+%f" 2>/dev/null | cut -d' ' -f2-)
#sleep 0.25

#mystring="$(cat /home/phil/.config/polybar/scripts/weatherinfo)"


#echo $(cat /home/phil/.config/polybar/scripts/weatherinfo)
